# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :feed_pug, :scopes,
  user: [
    default: true,
    module: FeedPug.Accounts.Scope,
    assign_key: :current_scope,
    access_path: [:user, :id],
    schema_key: :user_id,
    schema_type: :binary_id,
    schema_table: :users,
    test_data_fixture: FeedPug.AccountsFixtures,
    test_setup_helper: :register_and_log_in_user
  ]

config :feed_pug,
  ecto_repos: [FeedPug.Repo],
  generators: [timestamp_type: :utc_datetime, binary_id: true]

# When false, /users/register only accepts visitors who arrived via a valid
# invite token (/users/register?invite=...). Existing users mint invites at
# /users/invites. Default closed; dev/test open it, prod reads REGISTRATION_OPEN.
config :feed_pug, :registration_open, false

# Use UUIDv7 (time-ordered) binary primary/foreign keys everywhere. Schemas use
# `FeedPug.Schema` (UUIDv7 type, autogenerated app-side); migrations default to
# binary_id columns. Oban manages its own integer ids separately.
config :feed_pug, FeedPug.Repo,
  migration_primary_key: [name: :id, type: :binary_id],
  migration_foreign_key: [type: :binary_id]

# Oban: background feed polling
config :feed_pug, Oban,
  repo: FeedPug.Repo,
  queues: [feeds: 10],
  plugins: [
    {Oban.Plugins.Pruner, max_age: 60 * 60 * 24},
    {Oban.Plugins.Cron,
     crontab: [
       {"* * * * *", FeedPug.Workers.ScheduleFeeds}
     ]}
  ]

# Configure the endpoint
config :feed_pug, FeedPugWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: FeedPugWeb.ErrorHTML, json: FeedPugWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: FeedPug.PubSub,
  live_view: [signing_salt: "XD0bHcLs"]

# Configure the mailer
#
# By default it uses the "Local" adapter which stores the emails
# locally. You can see the emails in your browser, at "/dev/mailbox".
#
# For production it's recommended to configure a different adapter
# at the `config/runtime.exs`.
config :feed_pug, FeedPug.Mailer,
  adapter: Swoosh.Adapters.Local,
  from_name: "FeedPug",
  from_address: "noreply@localhost"

# Configure esbuild (the version is required)
config :esbuild,
  version: "0.25.4",
  feed_pug: [
    args:
      ~w(js/app.js --bundle --target=es2022 --outdir=../priv/static/assets/js --external:/fonts/* --external:/images/* --alias:@=.),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => [Path.expand("../deps", __DIR__), Mix.Project.build_path()]}
  ]

# Configure tailwind (the version is required)
config :tailwind,
  version: "4.1.12",
  feed_pug: [
    args: ~w(
      --input=assets/css/app.css
      --output=priv/static/assets/css/app.css
    ),
    cd: Path.expand("..", __DIR__)
  ]

# Configure Elixir's Logger
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Register the OPML extension so LiveView uploads accept `.opml` files.
config :mime, :types, %{"text/x-opml" => ["opml"]}

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
